# Generated by Django 5.2.17 on 2026-08-12 13:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='organizations.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='suppliers.category')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('legal_name', models.CharField(max_length=250, verbose_name='razón social')),
                ('trade_name', models.CharField(blank=True, max_length=250, verbose_name='nombre comercial')),
                ('tax_id', models.CharField(max_length=64, verbose_name='identificación fiscal')),
                ('country_code', models.CharField(default='CO', max_length=2, verbose_name='país')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('invited', 'Invitado'), ('active', 'Activo'), ('suspended', 'Suspendido'), ('archived', 'Archivado')], default='draft', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_suppliers', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='organizations.organization')),
            ],
            options={
                'ordering': ('legal_name',),
            },
        ),
        migrations.CreateModel(
            name='ExternalSupplierCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('system', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_codes', to='suppliers.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('is_primary', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='supplier',
            name='categories',
            field=models.ManyToManyField(related_name='suppliers', through='suppliers.SupplierCategory', to='suppliers.category'),
        ),
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('first_name', models.CharField(max_length=120, verbose_name='nombres')),
                ('last_name', models.CharField(blank=True, max_length=120, verbose_name='apellidos')),
                ('email', models.EmailField(max_length=254, verbose_name='correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='teléfono')),
                ('job_title', models.CharField(blank=True, max_length=120, verbose_name='cargo')),
                ('is_primary', models.BooleanField(default=False)),
                ('portal_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_contacts', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='suppliers.supplier')),
            ],
            options={
                'ordering': ('-is_primary', 'first_name', 'last_name'),
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_category_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='externalsuppliercode',
            constraint=models.UniqueConstraint(fields=('supplier', 'system', 'company', 'code'), name='unique_external_supplier_code'),
        ),
        migrations.AddConstraint(
            model_name='suppliercategory',
            constraint=models.UniqueConstraint(fields=('supplier', 'category'), name='unique_supplier_category'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('organization', 'tax_id'), name='unique_supplier_tax_id_per_org'),
        ),
        migrations.AddConstraint(
            model_name='suppliercontact',
            constraint=models.UniqueConstraint(fields=('supplier', 'email'), name='unique_contact_email_per_supplier'),
        ),
    ]
