# Generated by Django 5.2.17 on 2026-08-12 14:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('qualifications', '0003_qualificationcase_valid_until_casereview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('provider', models.CharField(max_length=80)),
                ('model_name', models.CharField(max_length=120)),
                ('prompt_version', models.CharField(default='document-v1', max_length=40)),
                ('status', models.CharField(choices=[('running', 'Ejecutando'), ('completed', 'Completado'), ('failed', 'Fallido')], max_length=20)),
                ('error', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_runs', to='qualifications.qualificationcase')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_runs', to='qualifications.evidencedocument')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_runs', to='organizations.organization')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_ai_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('field_code', models.CharField(max_length=200)),
                ('proposed_value', models.JSONField()),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('evidence_text', models.TextField()),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada')], default='pending', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_ai_suggestions', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='intelligence.aianalysisrun')),
            ],
            options={
                'ordering': ('-confidence', 'field_code'),
            },
        ),
    ]
