# Generated by Django 5.2.17 on 2026-08-12 13:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('name', models.CharField(max_length=120)),
                ('key_prefix', models.CharField(max_length=16)),
                ('key_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_credentials', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField(max_length=500)),
                ('secret', models.CharField(max_length=250)),
                ('event_types', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_subscriptions', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('key', models.CharField(max_length=150)),
                ('endpoint', models.CharField(max_length=150)),
                ('request_hash', models.CharField(max_length=64)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('response_body', models.JSONField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'key', 'endpoint'), name='unique_idempotency_key_per_endpoint')],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('event_id', models.UUIDField()),
                ('event_type', models.CharField(max_length=120)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('delivered', 'Entregado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integrations.webhooksubscription')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='integration_status_d4f89b_idx')],
                'constraints': [models.UniqueConstraint(fields=('subscription', 'event_id'), name='unique_webhook_delivery_per_event')],
            },
        ),
    ]
