# Generated by Django 5.2.17 on 2026-08-12 13:38

import django.db.models.deletion
import qualifications.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('name', models.CharField(max_length=200)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_templates', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='QualificationCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Enviado'), ('in_review', 'En revisión'), ('changes_requested', 'Correcciones solicitadas'), ('approved', 'Aprobado'), ('conditional', 'Condicional'), ('rejected', 'Rechazado'), ('suspended', 'Suspendido'), ('expired', 'Vencido')], default='draft', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_cases', to='organizations.organization')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_cases', to='suppliers.supplier')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='qualifications.qualificationtemplate')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('code', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=250)),
                ('instructions', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Fecha'), ('boolean', 'Sí/No'), ('select', 'Selección'), ('document', 'Documento')], max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qualification_requirements', to='suppliers.category')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='qualifications.qualificationtemplate')),
            ],
            options={
                'ordering': ('sort_order', 'code'),
            },
        ),
        migrations.CreateModel(
            name='EvidenceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('file', models.FileField(upload_to=qualifications.models.evidence_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidence_documents', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='qualifications.qualificationcase')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='qualifications.requirement')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RequirementResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('value', models.JSONField(blank=True, default=dict)),
                ('is_accepted', models.BooleanField(blank=True, null=True)),
                ('reviewer_comment', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='qualifications.qualificationcase')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='qualifications.requirement')),
            ],
        ),
        migrations.AddConstraint(
            model_name='qualificationtemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'name', 'version'), name='unique_qualification_template_version'),
        ),
        migrations.AddConstraint(
            model_name='qualificationcase',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('draft', 'submitted', 'in_review', 'changes_requested'))), fields=('supplier', 'template'), name='one_open_case_per_supplier_template'),
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.UniqueConstraint(fields=('template', 'code'), name='unique_requirement_code_per_template'),
        ),
        migrations.AddConstraint(
            model_name='requirementresponse',
            constraint=models.UniqueConstraint(fields=('case', 'requirement'), name='unique_response_per_requirement'),
        ),
    ]
