# Generated by Django 5.2.17 on 2026-08-12 13:46

import qualifications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencedocument',
            name='file',
            field=models.FileField(max_length=500, upload_to=qualifications.models.evidence_upload_path),
        ),
    ]
