# Generated by Django 5.2.17 on 2026-08-12 13:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0002_alter_evidencedocument_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qualificationcase',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CaseReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('decision', models.CharField(choices=[('changes_requested', 'Correcciones solicitadas'), ('approved', 'Aprobado'), ('conditional', 'Aprobado condicionalmente'), ('rejected', 'Rechazado')], max_length=30)),
                ('comment', models.TextField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='qualifications.qualificationcase')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualification_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
